// plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
<!--
  Matomo - free/libre analytics platform
  @link https://matomo.org
  @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
-->

<template>
  <div
    class="siteSelector piwikSelector borderedControl"
    :class="{'expanded': showSitesList, 'disabled': !hasMultipleSites}"
    v-focus-anywhere-but-here="{ blur: onBlur }"
  >
    <input
      v-if="name"
      type="hidden"
      :value="modelValue?.id"
      :name="name"
    />
    <a
      ref="selectorLink"
      @click="onClickSelector"
      @keydown="onPressEnter($event)"
      href="javascript:void(0)"
      :class="{'loading': isLoading}"
      class="title"
      tabindex="4"
      :title="selectorLinkTitle"
    >
      <span
        class="icon icon-arrow-bottom"
        :class="{'iconHidden': isLoading, 'collapsed': !showSitesList}"
      />
      <span>
        <span
          v-text="modelValue?.name || firstSiteName"
          v-if="modelValue?.name || !placeholder"
        />
        <span
          v-if="!modelValue?.name && placeholder"
          class="placeholder"
        >{{ placeholder }}</span>
      </span>
    </a>
    <div
      v-show="showSitesList"
      class="dropdown"
    >
      <div
        class="custom_select_search"
        v-show="autocompleteMinSites <= sites.length || searchTerm"
      >
        <input
          type="text"
          @click="searchTerm = '';loadInitialSites()"
          v-model="searchTerm"
          tabindex="4"
          class="websiteSearch inp browser-default"
          v-focus-if:[shouldFocusOnSearch]="{}"
          :placeholder="translate('General_Search')"
        />
        <img
          title="Clear"
          v-show="searchTerm"
          @click="searchTerm = '';loadInitialSites()"
          class="reset"
          src="plugins/CoreHome/images/reset_search.png"
        />
      </div>
      <div v-if="allSitesLocation === 'top' && showAllSitesItem">
        <AllSitesLink
          :href="urlAllSites"
          :all-sites-text="allSitesText"
          @click="onAllSitesClick($event)"
        />
      </div>
      <div class="custom_select_container">
        <ul
          class="custom_select_ul_list"
          @click="showSitesList = false"
        >
          <li
            @click="switchSite(site, $event)"
            v-show="!(!showSelectedSite && activeSiteId === site.idsite)"
            v-for="(site, index) in sites"
            :key="index"
          >
            <a
              @click="$event.preventDefault()"
              v-html="$sanitize(getMatchedSiteName(site.name))"
              tabindex="4"
              :href="getUrlForSiteId(site.idsite)"
              :title="site.name"
            />
          </li>
        </ul>
        <ul
          v-show="!sites.length && searchTerm"
          class="ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all
                 siteSelect"
        >
          <li class="ui-menu-item">
            <a
              class="ui-corner-all"
              tabindex="-1"
            >
              {{ translate('SitesManager_NotFound') + ' ' + searchTerm }}
            </a>
          </li>
        </ul>
      </div>
      <div v-if="allSitesLocation === 'bottom' && showAllSitesItem">
        <AllSitesLink
          :href="urlAllSites"
          :all-sites-text="allSitesText"
          @click="onAllSitesClick($event)"
        />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import FocusAnywhereButHere from '../FocusAnywhereButHere/FocusAnywhereButHere';
import FocusIf from '../FocusIf/FocusIf';
import AllSitesLink from './AllSitesLink.vue';
import Matomo from '../Matomo/Matomo';
import MatomoUrl from '../MatomoUrl/MatomoUrl';
import translate from '../translate';
import SitesStore, { Site } from './SitesStore';
import debounce from '../debounce';

interface SiteRef {
  id: string|number;
  name: string;
}

interface SiteSelectorState {
  searchTerm: string;
  showSitesList: boolean;
  isLoading: boolean;
  sites: Site[];
  autocompleteMinSites: null|number;
}

export default defineComponent({
  props: {
    modelValue: {
      Object,
      default: {
        id: Matomo.idSite,
        name: Matomo.helper.htmlDecode(Matomo.siteName),
      },
    },
    showSelectedSite: {
      type: Boolean,
      default: false,
    },
    showAllSitesItem: {
      type: Boolean,
      default: true,
    },
    switchSiteOnSelect: {
      type: Boolean,
      default: true,
    },
    onlySitesWithAdminAccess: {
      type: Boolean,
      default: false,
    },
    name: {
      type: String,
      default: '',
    },
    allSitesText: {
      type: String,
      default: translate('General_MultiSitesSummary'),
    },
    allSitesLocation: {
      type: String,
      default: 'bottom',
    },
    placeholder: String,
  },
  emits: ['update:modelValue', 'blur'],
  components: {
    AllSitesLink,
  },
  directives: {
    FocusAnywhereButHere,
    FocusIf,
  },
  watch: {
    searchTerm() {
      this.onSearchTermChanged();
    },
  },
  data(): SiteSelectorState {
    return {
      searchTerm: '',
      activeSiteId: Matomo.idSite,
      showSitesList: false,
      isLoading: false,
      sites: [],
      autocompleteMinSites: parseInt(Matomo.config.autocomplete_min_sites as string, 10),
    };
  },
  mounted() {
    window.initTopControls();

    this.loadInitialSites().then(() => {
      if ((!this.modelValue || !this.modelValue.id) && !this.hasMultipleSites && this.sites[0]) {
        this.$emit('update:modelValue', { id: this.sites[0].idsite, name: this.sites[0].name });
      }
    });

    const shortcutTitle = translate('CoreHome_ShortcutWebsiteSelector');
    Matomo.helper.registerShortcut('w', shortcutTitle, (event) => {
      if (event.altKey) {
        return;
      }
      if (event.preventDefault) {
        event.preventDefault();
      } else {
        event.returnValue = false; // IE
      }
      this.$refs.selectorLink.click();
      this.$refs.selectorLink.focus();
    });
  },
  computed: {
    shouldFocusOnSearch() {
      return (this.showSitesList && this.autocompleteMinSites <= this.sites.length)
        || this.searchTerm;
    },
    selectorLinkTitle() {
      return this.hasMultipleSites
        ? translate('CoreHome_ChangeCurrentWebsite', this.modelValue?.name || this.firstSiteName)
        : '';
    },
    hasMultipleSites() {
      return SitesStore.initialSites.value && SitesStore.initialSites.value.length > 1;
    },
    firstSiteName() {
      return this.sites && this.sites.length > 0 ? this.sites[0].name : '';
    },
    urlAllSites() {
      const newQuery = MatomoUrl.stringify({
        ...MatomoUrl.urlParsed.value,
        module: 'MultiSites',
        action: 'index',
        date: MatomoUrl.parsed.value.date,
        period: MatomoUrl.parsed.value.period,
      });
      return `?${newQuery}`;
    },
  },
  created() {
    this.searchSite = debounce(this.searchSite.bind(this));
  },
  methods: {
    onSearchTermChanged() {
      if (!this.searchTerm) {
        this.isLoading = false;
        this.loadInitialSites();
      } else {
        this.isLoading = true;
        this.searchSite(this.searchTerm);
      }
    },
    onAllSitesClick(event: MouseEvent) {
      this.switchSite({ idsite: 'all', name: this.allSitesText }, event);
      this.showSitesList = false;
    },
    switchSite(site: SiteRef, event: KeyboardEvent|MouseEvent) {
      // for Mac OS cmd key needs to be pressed, ctrl key on other systems
      const controlKey = navigator.userAgent.indexOf('Mac OS X') !== -1 ? event.metaKey : event.ctrlKey;

      if (event && controlKey && event.target && (event.target as HTMLLinkElement).href) {
        window.open((event.target as HTMLLinkElement).href, '_blank');
        return;
      }

      this.$emit('update:modelValue', { id: site.idsite, name: site.name });

      if (!this.switchSiteOnSelect || this.activeSiteId === site.idsite) {
        return;
      }

      SitesStore.loadSite(site.idsite);
    },
    onBlur() {
      this.showSitesList = false;
      this.$emit('blur');
    },
    onClickSelector() {
      if (this.hasMultipleSites) {
        this.showSitesList = !this.showSitesList;

        if (!this.isLoading && !this.searchTerm) {
          this.loadInitialSites();
        }
      }
    },
    onPressEnter(event: KeyboardEvent) {
      if (event.key !== 'Enter') {
        return;
      }

      event.preventDefault();

      this.showSitesList = !this.showSitesList;
      if (this.showSitesList && !this.isLoading) {
        this.loadInitialSites();
      }
    },
    getMatchedSiteName(siteName: string) {
      const index = siteName.toUpperCase().indexOf(this.searchTerm.toUpperCase());
      if (index === -1
        || this.isLoading // only highlight when we know the displayed results are for a search
      ) {
        return Matomo.helper.htmlEntities(siteName);
      }

      const previousPart = Matomo.helper.htmlEntities(siteName.substring(0, index));
      const lastPart = Matomo.helper.htmlEntities(
        siteName.substring(index + this.searchTerm.length),
      );

      return `${previousPart}<span class="autocompleteMatched">${this.searchTerm}</span>${lastPart}`;
    },
    loadInitialSites() {
      return SitesStore.loadInitialSites().then((sites) => {
        this.sites = sites || [];
      });
    },
    searchSite(term: string) {
      this.isLoading = true;

      SitesStore.searchSite(term, this.onlySitesWithAdminAccess).then((sites) => {
        if (term !== this.searchTerm) {
          return; // search term changed in the meantime
        }

        if (sites) {
          this.sites = sites;
        }
      }).finally(() => {
        this.isLoading = false;
      });
    },
    getUrlForSiteId(idSite: string|number) {
      const newQuery = MatomoUrl.stringify({
        ...MatomoUrl.urlParsed.value,
        segment: '',
        idSite,
      });

      const newHash = MatomoUrl.stringify({
        ...MatomoUrl.hashParsed.value,
        segment: '',
        idSite,
      });

      return `?${newQuery}#?${newHash}`;
    },
  },
});
</script>

// plugins/CoreHome/react/src/site-selector/SiteSelector.js
import * as React from 'react';
import ReactDOM from 'react-dom';
import classNames from 'classnames';
import {SiteSelectorService} from "./SiteSelectorService";
import {FocusAnywhereButHere} from '../common/FocusAnywhereButHere';

// TODO: note not using prop-types for validation
// TODO: note not using immutable.js

let shortcutRegistered = false;

class AllSitesLink extends React.PureComponent {
    render() {
        return (
            <div
                className='custom_select_all'
                onClick={this.props.onClick}
            >
                <a
                    onClick={event => event.preventDefault()}
                    href={this.getUrlAllSites()}
                    tabindex="4"
                    dangerouslySetInnerHTML={{__html: this.props.allSitesText}}
                />
            </div>
        );
    }

    getUrlAllSites() {
        const newParameters = 'module=MultiSites&action=index';
        return piwik.helper.getCurrentQueryStringWithParametersModified(newParameters);
    }
}

export class SiteSelector extends React.Component {
    constructor(props) {
        super(Object.assign({}, {
            autocompleteMinSites: piwik.config.autocomplete_min_sites,
            activeSiteId: piwik.idSite,
        }, props));

        this.state = {
            showSitesList: false,
            sites: [],
            selectedSite: {id: null, name: ''},
            isLoading: false,
            searchTerm: '',
        };

        this.searchInput = React.createRef();
        this.siteSelectorService = new SiteSelectorService({
            onlySitesWithAdminAccess: this.props.onlySitesWithAdminAccess,
        });
    }

    hasMultipleSites() {
        return this.sites.length > 1;
    }

    onClickSelectorLink() {
        if (!this.hasMultipleSites()) {
            return;
        }

        this.setState({
            showSitesList: !this.state.showSitesList,
        });

        if (!this.state.isLoading) {
            this.loadInitialSites();
        }
    }

    onKeyUpLink(event) {
        if (event.key.toLowerCase() === 'enter') {
            this.onClickSelectorLink();
        }
    }

    getLinkTitle() {
        if (!this.hasMultipleSites()) {
            return '';
        }

        return _pk_translate('CoreHome_ChangeCurrentWebsite', this.state.selectedSite.name || this.getFirstSiteName());
    }

    getFirstSiteName() {
        if (!this.state.sites.length) {
            return null;
        }

        return this.state.sites[0].name;
    }

    componentDidMount() {
        this.loadInitialSites().then(() => {
            if (!this.props.initialSelectedSite && !this.hasMultipleSites() && this.state.sites[0]) {
                this.setState({
                    selectedSite: {id: this.state.sites[0].idsite, name: this.state.sites[0].name},
                });
            }
        });

        this.registerShortcut();
    }

    registerShortcut() {
        if (shortcutRegistered) {
            return;
        }

        // done once per page
        piwikHelper.registerShortcut('w', _pk_translate('CoreHome_ShortcutWebsiteSelector'), function(event) {
            if (event.altKey) {
                return;
            }
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false; // IE
            }
            $('.siteSelector .title').trigger('click').focus();
        });

        shortcutRegistered = true;
    }

    componentDidUpdate(prevProps, prevState, snapshot) {
        this.focusInputIfNeeded();
    }

    focusInputIfNeeded() {
        if (this.state.showSitesList && (this.props.auto <= this.sites.length || this.state.searchTerm)) {
            this.searchInput.current.focus();
        }
    }

    onClickAllSitesLink(event) {
        this.switchSite({idsite: 'all', name: this.allSitesText}, event);
        this.showSitesList = false;
    }

    getUrlForSiteId(idSite) {
        const idSiteParam   = 'idSite=' + idSite;
        const newParameters = 'segment=&' + idSiteParam;
        const hash = piwik.broadcast.isHashExists() ? piwik.broadcast.getHashFromUrl() : "";
        return piwik.helper.getCurrentQueryStringWithParametersModified(newParameters) +
            '#' + piwik.helper.getQueryStringWithParametersModified(hash.substring(1), newParameters);
    }

    async loadInitialSites() {
        this.setState({ isLoading: true });

        const sites = await this.siteSelectorService.loadInitialSites();

        this.setState({
            sites,
            isLoading: false,
        });
    }

    async searchSite() {
        this.setState({ isLoading: true });

        const sites = await this.siteSelectorService.searchSite(this.state.searchTerm);
        this.setState({
            sites: sites,
            isLoading: false,
        });
    }

    switchSite(site, event) {
        // for Mac OS cmd key needs to be pressed, ctrl key on other systems
        const controlKey = navigator.userAgent.indexOf("Mac OS X") !== -1 ? event.metaKey : event.ctrlKey;
        if (event && controlKey && event.target && event.target.href) {
            window.open(event.target.href, "_blank");
            return;
        }

        this.setState({
            selectedSite: {id: site.idsite, name: site.name},
        });

        if (!this.props.switchSiteOnSelect || this.props.activeSiteId === site.idsite) {
            return;
        }

        this.loadSite(site.idsite);
    }

    loadSite(idSite) {
        if (idSite === 'all') {
            document.location.href = piwikHelper.getCurrentQueryStringWithParametersModified(piwikHelper.getQueryStringFromParameters({
                module: 'MultiSites',
                action: 'index',
                date: piwik.currentDateString,
                period: piwik.period,
            }));
        } else {
            piwik.broadcast.propagateNewPage('segment=&idSite=' + idSite, false);
        }
    }

    render() {
        return (
            <FocusAnywhereButHere onLoseFocus={() => this.setState({ showSitesList: false })}>
                <div
                    className={classNames("siteSelector", "piwikSelector", "borderedControl", {
                        expanded: this.state.showSitesList,
                        disabled: !this.hasMultipleSites()
                    })}
                >
                    {this.renderSelectedSiteInput()}
                </div>

                <a
                    onClick={this.onClickSelectorLink.bind(this)}
                    onKeyUp={this.onKeyUpLink.bind(this)}
                    href="javascript:void(0)"
                    title={this.getLinkTitle()}
                    className={classNames({title: true, loading: this.state.isLoading})}
                    tabIndex={4}
                >
                    <span className={classNames('icon', 'icon-arrow-bottom', {iconHidden: this.state.isLoading, collapsed: !this.state.showSitesList})}/>
                    <span>
                        {(this.state.selectedSite.name || !this.props.placeholder) &&
                            <span>
                                {this.state.selectedSite.name || this.getFirstSiteName()}
                            </span>
                        }
                        {(!this.state.selectedSite.name && this.props.placeholder) &&
                            <span className="placeholder">
                                {this.props.placeholder}
                            </span>
                        }
                    </span>
                </a>

                <div hidden={this.props.showSitesList} className="dropdown">
                    <div className={"custom_select_search"} hidden={this.props.autocompleteMinSites <= this.state.sites.length || this.state.searchTerm}>
                        <input
                            type="text"
                            ref={this.searchInput}
                            onClick={() => this.setState({searchTerm: ''})}
                            onChange={(value) => {
                                this.setState({searchTerm: value});
                                this.searchSite();
                            }}
                            placeholder={_pk_translate('General_Search')}
                            tabIndex={4}
                            className={"websiteSearch inp browser-default"}
                        />
                        <img
                            title={_pk_translate("General_Clear")}
                            hidden={!!this.state.searchTerm}
                            onClick={() => {
                                this.setState({ searchTerm: '' });
                                this.loadInitialSites();
                            }}
                            className={"reset"}
                            src={"plugins/CoreHome/images/reset_search.png"}
                        />
                    </div>

                    {(this.props.allSitesLocation === 'top' && this.props.showAllSitesItem) &&
                        <AllSitesLink onClick={this.onClickAllSitesLink.bind(this)} allSitesText={this.props.allSitesText} />}

                    <div className={"custom_select_container"}>
                        <ul className="custom_select_ul_list" onClick={() => this.setState({ showSitesList: false })}>
                            {this.state.sites.map(site => this.renderSiteRow(site))}
                        </ul>
                        <ul
                            hidden={!this.state.sites.length && this.state.searchTerm}
                            className={"ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all siteSelect"}
                        >
                            <li className="ui-menu-item">
                                <a className="ui-corner-all" tabIndex={-1}>
                                    {`${_pk_translate('SitesManager_NotFound')} ${this.state.searchTerm}`}
                                </a>
                            </li>
                        </ul>
                    </div>

                    {(this.props.allSitesLocation === 'bottom' && this.props.showAllSitesItem) &&
                        <AllSitesLink onClick={this.onClickAllSitesLink.bind(this)} allSitesText={this.props.allSitesText} />}
                </div>
            </FocusAnywhereButHere>
        );
    }

    renderSelectedSiteInput() {
        if (!this.props.inputName) {
            return null;
        }

        return <input type="hidden" name={this.props.inputName} value={this.state.selectedSite.id}/>;
    }

    renderSiteRow(site) {
        const parts = !this.state.searchTerm ? [site.name] : site.name.split(this.state.searchTerm);

        return (
            <li
                key={site.idsite}
                onClick={(event) => this.props.switchSite(site, event)}
                hidden={!this.state.showSelectedSite && this.props.activeSiteId === site.idsite}
            >
                <a
                    onClick={event => event.preventDefault()}
                    href={this.getUrlForSiteId(site.idsite)}
                    title={site.name}
                    tabIndex={4}
                >
                    {parts.map((w, i) => {
                        if (i === 0) {
                            return w;
                        }

                        return [
                            <span key={i} className="autocompleteMatched">{this.state.searchTerm}</span>,
                            w,
                        ];
                    })}
                </a>
            </li>
        );
    }

    static renderTo(element, props) {
        ReactDOM.render(<SiteSelector {...props}/>, element);
    }
}
