// plugins/CoreHome/react/src/ContentBlock/ContentBlock.js
import * as React from 'react';
import ReactDOM from 'react-dom';
import classNames from 'classnames';
import {RateFeature} from '../rate-feature/RateFeature';
import {EnrichedHeadline} from "../enriched-headline/EnrichedHeadline";

const { piwik, _pk_translate, $ } = window;

let adminContent = null;

export class ContentBlock extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            helpText: this.props.helpText,
            feature: this.props.feature,
        }

        this.childContainer = React.createRef();
    }

    componentDidMount() {
        const $root = $(this.childContainer.current);

        const inlineHelp = $root.find('.contentHelp');
        if (inlineHelp.length) {
            this.setState({ helpText: inlineHelp.html() });
            inlineHelp.remove();
        }

        if (this.state.feature && (this.state.feature===true || this.state.feature ==='true')) {
            this.state.feature = this.props.contentTitle;
        }

        if (adminContent === null) {
            // cache admin node for further content blocks
            adminContent = $('#content.admin');
        }

        let contentTopPosition = false;

        if (adminContent.length) {
            contentTopPosition = adminContent.offset().top;
        }

        if (contentTopPosition || contentTopPosition === 0) {
            let parents = $root.parentsUntil('.col', '[piwik-widget-loader]');
            let topThis;
            if (parents.length) {
                // when shown within the widget loader, we need to get the offset of that element
                // as the widget loader might be still shown. Would otherwise not position correctly
                // the widgets on the admin home page
                topThis = parents.offset().top;
            } else {
                topThis = $root.offset().top;
            }

            if ((topThis - contentTopPosition) < 17) {
                // we make sure to display the first card with no margin-top to have it on same as line as
                // navigation
                $root.css('marginTop', '0');
            }
        }
    }

    render() {
        return [
            this.props.anchor && <a key={0} id={this.props.anchor}/>,
            <div key={1} className="card">
                <div className="card-content">
                    {(this.props.contentTitle && !this.state.feature && !this.props.helpUrl && !this.state.helpText) &&
                        <h2 className="card-title">{this.props.contentTitle}</h2>}

                    {this.props.contentTitle && (this.state.feature || this.props.helpUrl || this.state.helpText) &&
                        <h2 className="card-title">
                            <EnrichedHeadline
                                featureName={this.state.feature}
                                helpUrl={this.props.helpUrl}
                                inlineHelp={this.state.helpText}
                            >
                                {this.props.contentTitle}
                            </EnrichedHeadline>
                        </h2>
                    }
                    <div ref={this.childContainer}>
                        {this.props.children}
                    </div>
                </div>
            </div>
        ];
    }

    static renderTo(element, props) {
        ReactDOM.render(<ContentBlock {...props}/>, element);
    }
}

// plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
<!--
  Matomo - free/libre analytics platform
  @link https://matomo.org
  @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
-->

<template>
  <div class="card" ref="root">
    <div class="card-content">
      <h2
        v-if="contentTitle && !actualFeature && !helpUrl && !actualHelpText"
        class="card-title"
      >{{ contentTitle }}</h2>
      <h2
        v-if="contentTitle && (actualFeature || helpUrl || actualHelpText)"
        class="card-title"
      >
        <EnrichedHeadline
          :feature-name="actualFeature"
          :help-url="helpUrl"
          :inline-help="actualHelpText"
        >
          {{ contentTitle }}
        </EnrichedHeadline>
      </h2>
      <div ref="content">
        <slot />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import EnrichedHeadline from '../EnrichedHeadline/EnrichedHeadline.vue';

let adminContent: HTMLElement|null = null;

const { $ } = window;

export default defineComponent({
  props: {
    contentTitle: String,
    feature: String,
    helpUrl: String,
    helpText: String,
    anchor: String,
  },
  components: {
    EnrichedHeadline,
  },
  data() {
    return {
      actualFeature: this.feature,
      actualHelpText: this.helpText,
    };
  },
  watch: {
    feature(newValue: string) {
      this.actualFeature = newValue;
    },
    helpText(newValue: string) {
      this.actualHelpText = newValue;
    },
  },
  mounted() {
    const root = this.$refs.root as HTMLElement;
    const content = this.$refs.content as HTMLElement;

    if (this.anchor && root && root.parentElement) {
      const anchorElement = document.createElement('a');
      anchorElement.id = this.anchor;
      $(root.parentElement).prepend(anchorElement);
    }

    setTimeout(() => {
      const inlineHelp = content.querySelector('.contentHelp');
      if (inlineHelp) {
        this.actualHelpText = inlineHelp.innerHTML;
        inlineHelp.remove();
      }
    }, 0);

    if (this.actualFeature && this.actualFeature === 'true') {
      this.actualFeature = this.contentTitle;
    }

    if (adminContent === null) {
      // cache admin node for further content blocks
      adminContent = document.querySelector('#content.admin');
    }

    let contentTopPosition: number|null = null;
    if (adminContent) {
      contentTopPosition = adminContent.offsetTop;
    }

    if (contentTopPosition || contentTopPosition === 0) {
      const parents = root.closest('[piwik-widget-loader]') as HTMLElement;

      // when shown within the widget loader, we need to get the offset of that element
      // as the widget loader might be still shown. Would otherwise not position correctly
      // the widgets on the admin home page
      const topThis = parents ? parents.offsetTop : root.offsetTop;

      if (topThis - contentTopPosition < 17) {
        // we make sure to display the first card with no margin-top to have it on same as line as
        // navigation
        root.style.marginTop = '0';
      }
    }
  },
});
</script>
