// plugins/CoreHome/react/src/enriched-headline/EnrichedHeadline.js
import * as React from 'react';
import ReactDOM from 'react-dom';
import classNames from 'classnames';
import {RateFeature} from '../rate-feature/RateFeature';

const { piwik, _pk_translate, $ } = window;

export class EnrichedHeadline extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            showReportGenerated: false,
            showInlineHelp: false,
            showIcons: false,
            inlineHelp: props.inlineHelp,
            featureName: props.featureName,
        };

        this.root = React.createRef();
        this.title = React.createRef();
        this.titleLink = React.createRef();
    }

    componentDidMount() {
        // TODO: bad,bad,using jquery.
        let $root = $(this.root.current);

        if (!this.state.inlineHelp && !this.inlineHelpDeduced) {
            let $helpNode = $('.inlineHelp', this.title.current || this.titleLink.current);
            if ((!$helpNode || !$helpNode.length) && $root.next()) {
                // hack for reports :(
                $helpNode = $root.next().find('.reportDocumentation');
            }

            if ($helpNode && $helpNode.length) {
                // hackish solution to get binded html of p tag within the help node
                // at this point the ng-bind-html is not yet converted into html when report is not
                // initially loaded. Using $compile doesn't work. So get and set it manually
                if ($.trim($helpNode.text())) {
                    this.setState({ inlineHelp: $.trim($helpNode.html()) });
                }

                $helpNode.remove();
            }
        }

        if (!this.state.featureName && !this.featureNameDeduced) {
            let deducedFeatureName = $root.find('.title').first().text();
            if (deducedFeatureName) {
                this.setState({featureName: $.trim(deducedFeatureName)});
            }
        }

        if (this.props.reportGenerated && piwik.periods.parse(piwik.period, piwik.currentDateString).containsToday()) {
            $root.find('.report-generated').first().tooltip({
                track: true,
                content: this.props.reportGenerated,
                items: 'div',
                show: false,
                hide: false
            });

            this.setState({
                showReportGenerated: 1,
            });
        }
    }

    render() {
        return (
            <div
                ref={this.root}
                className="enrichedHeadline"
                onMouseEnter={() => this.setState({ showIcons: true })}
                onMouseLeave={() => this.setState({ showIcons: false })}
            >
                {!this.props.editUrl && <div ref={this.title} className="title" tabIndex="6">
                    {this.props.children}
                </div>}

                {this.props.editUrl && <a ref={this.titleLink} className="title" href={this.props.editUrl} title={_pk_translate('CoreHome_ClickToEditX', [this.state.featureName])}>
                    {this.props.children}
                </a>}

                <span hidden={!this.state.showIcons && !this.state.showInlineHelp} className={"iconsBar"}>
                    {this.props.helpUrl && !this.state.inlineHelp && <a
                        rel="noreferrer noopener"
                        target="_blank"
                        href={this.props.helpUrl}
                        title={_pk_translate('CoreHome_ExternalHelp')}
                        className="helpIcon"
                    >
                        <span className="icon-help"/>
                    </a>}

                    {this.state.inlineHelp && <a
                        title={_pk_translate('General_Help')}
                        onClick={() => this.setState({ showInlineHelp: !this.state.showInlineHelp })}
                        className={classNames("helpIcon", { active: this.state.showInlineHelp })}
                    >
                        <span className="icon-help"/>
                    </a>}

                    <div className="ratingIcons"
                         title={this.state.featureName}>
                        <RateFeature title={this.state.featureName}/>
                    </div>
                </span>

                {this.state.showReportGenerated && <div className="icon-clock report-generated"/>}

                {this.state.showInlineHelp && <div className="inlineHelp">
                    <div dangerouslySetInnerHTML={{__html: this.state.inlineHelp}}/>
                    {this.props.helpUrl && <a
                        rel={"noreferrer noopener"}
                        target={"_blank"}
                        href={this.props.helpUrl}
                        className={"readMore"}
                    >
                        {_pk_translate('General_MoreDetails')}
                    </a>}
                </div>}
            </div>
        );
    }

    static renderTo(element, props) {
        ReactDOM.render(<EnrichedHeadline {...props}/>, element);
    }
}

// plugins/CoreHome/angular/src/lib/enriched-headline/enriched-headline.component.ts
import {
    AfterContentInit,
    Component,
    ContentChild,
    ElementRef,
    EventEmitter,
    Input,
    OnInit,
    Output
} from "@angular/core";

declare var piwik: any;
declare var $: any;

@Component({
    selector: 'enriched-headline',
    template: `
    <div
        class="enrichedHeadline"
        (mouseenter)="showIcons = true"
        (mouseleave)="showIcons = false"
    >
        <div *ngIf="!editUrl" class="title" tabindex="6">
            <ng-content></ng-content>
        </div>
        <a *ngIf="editUrl" class="title" [attr.href]="editUrl" title="{{'CoreHome_ClickToEditX'|translate:featureName}}">
            <ng-content></ng-content>
        </a>
        
        <span *ngIf="showIcons || showInlineHelp" class="iconsBar">
            <a
                *ngIf="helpUrl && !inlineHelp"
                rel="noreferrer noopener"
                target="_blank"
                [attr.href]="helpUrl"
                title="{{ 'CoreHome_ExternalHelp'|translate }}"
                class="helpIcon"
            >
                <span class="icon-help"></span>
            </a>
            
            <a
                *ngIf="inlineHelp"
                title="{{ 'General_Help'|translate }}"
                (click)="showInlineHelp=!showInlineHelp"
                class="helpIcon"
                [class.active]="showInlineHelp"
            >
                <span class="icon-help"></span>
            </a>
            
            <rate-feature class="ratingIcons" title="{{ featureName }}"></rate-feature>
        </span>

        <div *ngIf="showReportGenerated" class="icon-clock report-generated"></div>

        <div class="inlineHelp" *ngIf="showInlineHelp">
            <div [innerHTML]="inlineHelp"></div>
            <a
                    *ngIf="helpUrl"
                    rel="noreferrer noopener"
                    target="_blank"
                    [attr.href]="helpUrl"
                    class="readMore"
            >
                {{ 'General_MoreDetails'|translate }}
            </a>
        </div>
    </div>
    `,
})
export class EnrichedHeadlineComponent implements AfterContentInit {
    constructor(private componentElement: ElementRef) {}

    @Input() helpUrl: string = '';
    @Input() editUrl: string = '';
    @Input() reportGenerated?: string;
    @Input() featureName: string = '';
    @Input() inlineHelp?: string = '';
    @Input() showReportGenerated: boolean = false;

    showIcons: boolean = false;
    showInlineHelp: boolean = false;

    ngAfterContentInit(): void {
        this.findInlineHelpInContentIfRequired();
        this.findFeatureNameInContentIfRequired();
        this.addReportGeneratedTooltip();
    }

    private addReportGeneratedTooltip() {
        if (!this.reportGenerated) {
            return;
        }

        if (!piwik.periods.parse(piwik.period, piwik.currentDateString).coinsToday()) {
            return;
        }

        const reportGeneratedElement = this.componentElement.nativeElement.querySelector('.report-generated');
        $(reportGeneratedElement).tooltip({
            track: true,
            content: this.reportGenerated,
            items: 'div',
            show: false,
            hide: false,
        });

        this.showReportGenerated = true;
    }

    private findFeatureNameInContentIfRequired() {
        if (this.featureName) {
            return;
        }

        this.featureName = $.trim($(this.componentElement.nativeElement).find('.title').first().text());
    }

    private findInlineHelpInContentIfRequired() {
        if (this.inlineHelp) {
            return;
        }

        // TODO: jquery should not be used in angular forever, it all must be replaced.
        const element = $(this.componentElement.nativeElement);
        let helpNode = $('.title .inlineHelp', this.componentElement.nativeElement);

        if ((!helpNode || !helpNode.length) && element.next()) {
            // hack for reports :(
            helpNode = element.next().find('.reportDocumentation');
        }

        if (helpNode && helpNode.length) {
            // hackish solution to get binded html of p tag within the help node
            // at this point the ng-bind-html is not yet converted into html when report is not
            // initially loaded. Using $compile doesn't work. So get and set it manually
            const helpParagraph = $('p[ng-bind-html]', helpNode); // TODO: this will eventually not work as more components are converted
            console.log(helpParagraph.html());
/*
            if (helpParagraph.length) {
                helpParagraph.html($parse(helpParagraph.attr('ng-bind-html')));
            }

            if ($.trim(helpNode.text())) {
                scope.inlineHelp = $.trim(helpNode.html());
            }
            helpNode.remove();
            */
        }
    }
}
