// plugins/CoreHome/react/src/site-selector/SiteSelector.js
import * as React from 'react';
import ReactDOM from 'react-dom';
import classNames from 'classnames';
import {SiteSelectorService} from "./SiteSelectorService";
import {FocusAnywhereButHere} from '../common/FocusAnywhereButHere';

// TODO: note not using prop-types for validation
// TODO: note not using immutable.js

let shortcutRegistered = false;

class AllSitesLink extends React.PureComponent {
    render() {
        return (
            <div
                className='custom_select_all'
                onClick={this.props.onClick}
            >
                <a
                    onClick={event => event.preventDefault()}
                    href={this.getUrlAllSites()}
                    tabindex="4"
                    dangerouslySetInnerHTML={{__html: this.props.allSitesText}}
                />
            </div>
        );
    }

    getUrlAllSites() {
        const newParameters = 'module=MultiSites&action=index';
        return piwik.helper.getCurrentQueryStringWithParametersModified(newParameters);
    }
}

export class SiteSelector extends React.Component {
    constructor(props) {
        super(Object.assign({}, {
            autocompleteMinSites: piwik.config.autocomplete_min_sites,
            activeSiteId: piwik.idSite,
        }, props));

        this.state = {
            showSitesList: false,
            sites: [],
            selectedSite: {id: null, name: ''},
            isLoading: false,
            searchTerm: '',
        };

        this.searchInput = React.createRef();
        this.siteSelectorService = new SiteSelectorService({
            onlySitesWithAdminAccess: this.props.onlySitesWithAdminAccess,
        });
    }

    hasMultipleSites() {
        return this.sites.length > 1;
    }

    onClickSelectorLink() {
        if (!this.hasMultipleSites()) {
            return;
        }

        this.setState({
            showSitesList: !this.state.showSitesList,
        });

        if (!this.state.isLoading) {
            this.loadInitialSites();
        }
    }

    onKeyUpLink(event) {
        if (event.key.toLowerCase() === 'enter') {
            this.onClickSelectorLink();
        }
    }

    getLinkTitle() {
        if (!this.hasMultipleSites()) {
            return '';
        }

        return _pk_translate('CoreHome_ChangeCurrentWebsite', this.state.selectedSite.name || this.getFirstSiteName());
    }

    getFirstSiteName() {
        if (!this.state.sites.length) {
            return null;
        }

        return this.state.sites[0].name;
    }

    componentDidMount() {
        this.loadInitialSites().then(() => {
            if (!this.props.initialSelectedSite && !this.hasMultipleSites() && this.state.sites[0]) {
                this.setState({
                    selectedSite: {id: this.state.sites[0].idsite, name: this.state.sites[0].name},
                });
            }
        });

        this.registerShortcut();
    }

    registerShortcut() {
        if (shortcutRegistered) {
            return;
        }

        // done once per page
        piwikHelper.registerShortcut('w', _pk_translate('CoreHome_ShortcutWebsiteSelector'), function(event) {
            if (event.altKey) {
                return;
            }
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false; // IE
            }
            $('.siteSelector .title').trigger('click').focus();
        });

        shortcutRegistered = true;
    }

    componentDidUpdate(prevProps, prevState, snapshot) {
        this.focusInputIfNeeded();
    }

    focusInputIfNeeded() {
        if (this.state.showSitesList && (this.props.auto <= this.sites.length || this.state.searchTerm)) {
            this.searchInput.current.focus();
        }
    }

    onClickAllSitesLink(event) {
        this.switchSite({idsite: 'all', name: this.allSitesText}, event);
        this.showSitesList = false;
    }

    getUrlForSiteId(idSite) {
        const idSiteParam   = 'idSite=' + idSite;
        const newParameters = 'segment=&' + idSiteParam;
        const hash = piwik.broadcast.isHashExists() ? piwik.broadcast.getHashFromUrl() : "";
        return piwik.helper.getCurrentQueryStringWithParametersModified(newParameters) +
            '#' + piwik.helper.getQueryStringWithParametersModified(hash.substring(1), newParameters);
    }

    async loadInitialSites() {
        this.setState({ isLoading: true });

        const sites = await this.siteSelectorService.loadInitialSites();

        this.setState({
            sites,
            isLoading: false,
        });
    }

    async searchSite() {
        this.setState({ isLoading: true });

        const sites = await this.siteSelectorService.searchSite(this.state.searchTerm);
        this.setState({
            sites: sites,
            isLoading: false,
        });
    }

    switchSite(site, event) {
        // for Mac OS cmd key needs to be pressed, ctrl key on other systems
        const controlKey = navigator.userAgent.indexOf("Mac OS X") !== -1 ? event.metaKey : event.ctrlKey;
        if (event && controlKey && event.target && event.target.href) {
            window.open(event.target.href, "_blank");
            return;
        }

        this.setState({
            selectedSite: {id: site.idsite, name: site.name},
        });

        if (!this.props.switchSiteOnSelect || this.props.activeSiteId === site.idsite) {
            return;
        }

        this.loadSite(site.idsite);
    }

    loadSite(idSite) {
        if (idSite === 'all') {
            document.location.href = piwikHelper.getCurrentQueryStringWithParametersModified(piwikHelper.getQueryStringFromParameters({
                module: 'MultiSites',
                action: 'index',
                date: piwik.currentDateString,
                period: piwik.period,
            }));
        } else {
            piwik.broadcast.propagateNewPage('segment=&idSite=' + idSite, false);
        }
    }

    render() {
        return (
            <FocusAnywhereButHere onLoseFocus={() => this.setState({ showSitesList: false })}>
                <div
                    className={classNames("siteSelector", "piwikSelector", "borderedControl", {
                        expanded: this.state.showSitesList,
                        disabled: !this.hasMultipleSites()
                    })}
                >
                    {this.renderSelectedSiteInput()}
                </div>

                <a
                    onClick={this.onClickSelectorLink.bind(this)}
                    onKeyUp={this.onKeyUpLink.bind(this)}
                    href="javascript:void(0)"
                    title={this.getLinkTitle()}
                    className={classNames({title: true, loading: this.state.isLoading})}
                    tabIndex={4}
                >
                    <span className={classNames('icon', 'icon-arrow-bottom', {iconHidden: this.state.isLoading, collapsed: !this.state.showSitesList})}/>
                    <span>
                        {(this.state.selectedSite.name || !this.props.placeholder) &&
                            <span>
                                {this.state.selectedSite.name || this.getFirstSiteName()}
                            </span>
                        }
                        {(!this.state.selectedSite.name && this.props.placeholder) &&
                            <span className="placeholder">
                                {this.props.placeholder}
                            </span>
                        }
                    </span>
                </a>

                <div hidden={this.props.showSitesList} className="dropdown">
                    <div className={"custom_select_search"} hidden={this.props.autocompleteMinSites <= this.state.sites.length || this.state.searchTerm}>
                        <input
                            type="text"
                            ref={this.searchInput}
                            onClick={() => this.setState({searchTerm: ''})}
                            onChange={(value) => {
                                this.setState({searchTerm: value});
                                this.searchSite();
                            }}
                            placeholder={_pk_translate('General_Search')}
                            tabIndex={4}
                            className={"websiteSearch inp browser-default"}
                        />
                        <img
                            title={_pk_translate("General_Clear")}
                            hidden={!!this.state.searchTerm}
                            onClick={() => {
                                this.setState({ searchTerm: '' });
                                this.loadInitialSites();
                            }}
                            className={"reset"}
                            src={"plugins/CoreHome/images/reset_search.png"}
                        />
                    </div>

                    {(this.props.allSitesLocation === 'top' && this.props.showAllSitesItem) &&
                        <AllSitesLink onClick={this.onClickAllSitesLink.bind(this)} allSitesText={this.props.allSitesText} />}

                    <div className={"custom_select_container"}>
                        <ul className="custom_select_ul_list" onClick={() => this.setState({ showSitesList: false })}>
                            {this.state.sites.map(site => this.renderSiteRow(site))}
                        </ul>
                        <ul
                            hidden={!this.state.sites.length && this.state.searchTerm}
                            className={"ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all siteSelect"}
                        >
                            <li className="ui-menu-item">
                                <a className="ui-corner-all" tabIndex={-1}>
                                    {`${_pk_translate('SitesManager_NotFound')} ${this.state.searchTerm}`}
                                </a>
                            </li>
                        </ul>
                    </div>

                    {(this.props.allSitesLocation === 'bottom' && this.props.showAllSitesItem) &&
                        <AllSitesLink onClick={this.onClickAllSitesLink.bind(this)} allSitesText={this.props.allSitesText} />}
                </div>
            </FocusAnywhereButHere>
        );
    }

    renderSelectedSiteInput() {
        if (!this.props.inputName) {
            return null;
        }

        return <input type="hidden" name={this.props.inputName} value={this.state.selectedSite.id}/>;
    }

    renderSiteRow(site) {
        const parts = !this.state.searchTerm ? [site.name] : site.name.split(this.state.searchTerm);

        return (
            <li
                key={site.idsite}
                onClick={(event) => this.props.switchSite(site, event)}
                hidden={!this.state.showSelectedSite && this.props.activeSiteId === site.idsite}
            >
                <a
                    onClick={event => event.preventDefault()}
                    href={this.getUrlForSiteId(site.idsite)}
                    title={site.name}
                    tabIndex={4}
                >
                    {parts.map((w, i) => {
                        if (i === 0) {
                            return w;
                        }

                        return [
                            <span key={i} className="autocompleteMatched">{this.state.searchTerm}</span>,
                            w,
                        ];
                    })}
                </a>
            </li>
        );
    }

    static renderTo(element, props) {
        ReactDOM.render(<SiteSelector {...props}/>, element);
    }
}

// plugins/CoreHome/angular/src/lib/siteselector/siteselector.component.ts
import {
    Component,
    ElementRef,
    EventEmitter,
    Input,
    OnInit,
    Output,
    QueryList,
    SecurityContext,
    SimpleChanges,
    ViewChild,
    ViewChildren
} from '@angular/core';
import {Site} from "../site-store/site";
import {BehaviorSubject, Observable} from "rxjs";
import {combineLatest, filter, map} from "rxjs/operators";
import {SitesService} from "../site-store/sites.service";
import {DomSanitizer} from "@angular/platform-browser";

// TODO: put this in a types file
declare var _pk_translate : (v: string) => string;

const piwik: any = (window as any).piwik;
const piwikHelper: any = (window as any).piwikHelper;

@Component({
    selector: 'site-selector-all-sites-link',
    template: `
        <div
            (click)="onClickLink.next($event)"
            class="custom_select_all"
        >
            <a 
                [attr.href]="getUrlAllSites()"
                (click)="$event.preventDefault()"
                tabindex="4"
                [innerHTML]="allSitesText"
            >
            </a>
        </div>
    `,
})
export class SiteSelectorAllSitesLink {
    @Input() allSitesText: string = '';
    @Output() onClickLink: EventEmitter<MouseEvent> = new EventEmitter<MouseEvent>();

    getUrlAllSites() {
        const newParameters = 'module=MultiSites&action=index';
        return (window as any).piwik.helper.getCurrentQueryStringWithParametersModified(newParameters);
    }
}

interface SiteRef {
    id: string|number;
    name: string;
}

@Component({
    selector: 'piwik-siteselector',
    template: `<div #rootdiv
                    focusAnywhereButHere
                    (onLoseFocus)="showSitesList=false"
                    class="siteSelector piwikSelector borderedControl"
                    [class.expanded]="showSitesList"
                    [class.disabled]="_hasOnlyOneSite$ | async"
>
        <input *ngIf="name" type="hidden" [attr.name]="name" [value]="selectedSite?.id"/>

        <a
                #selectedSiteDisplay
                (click)="onClickSelector()"
                (keyup.enter)="onClickSelector()"
                href="javascript:void(0)"
                [attr.title]="(_hasMultipleWebsites$ | async) ? ('CoreHome_ChangeCurrentWebsite'|translate) : ''"
                class="title"
                [class.loading]="isLoading"
                tabindex="4"
        >
            <span
                class="icon icon-arrow-bottom"
                [class.iconHidden]="isLoading"
                [class.collapsed]="!showSitesList"
            >
            </span>
            <span *ngIf="selectedSite?.name || !placeholder">{{ selectedSite?.name || (_firstSiteName$|async) }}</span>
            <span *ngIf="!selectedSite?.name && placeholder">{{ placeholder }}</span>
        </a>

        <div *ngIf="showSitesList" class="dropdown">
            <div class="custom_select_search" *ngIf="((autocompleteMinSites$|async) || 0) <= ((_sitesLength$|async) || 0) || searchTerm">
                <input
                        #customSelectInput
                        type="text"
                        (click)="searchTerm=''"
                        [(ngModel)]="searchTerm"
                        (change)="searchSite()"
                        [attr.placeholder]="'General_Search'|translate"
                        tabindex="4"
                        class="websiteSearch inp browser-default"
                />
                <!-- TODO: translate Clear? -->
                <img title="Clear"
                     *ngIf="searchTerm"
                     (click)="clearSearchTerm()"
                     class="reset"
                     src="plugins/CoreHome/images/reset_search.png"
                />
            </div>

            <div *ngIf="allSitesLocation=='top' && showAllSitesItem">
                <site-selector-all-sites-link
                        [allSitesText]="allSitesText"
                        (onClickLink)="onClickAllSitesLink($event)"
                >
                </site-selector-all-sites-link>
            </div>

            <div class="custom_select_container">
                <ul class="custom_select_ul_list" (click)="showSitesList=false">
                    <!-- !showSelectedSite && activeSiteId==site.idsite -->
                    <li
                            *ngFor="let site of (_sites$|async)"
                            (click)="switchSite(site, $event)"
                            [hidden]="!showSelectedSite && activeSiteId == site.idsite"
                    >
                        <a
                                #listLink
                                (click)="$event.preventDefault()"
                                [attr.href]="getUrlForSiteId(site.idsite)"
                                [attr.title]="site.name"
                                [innerHTML]="site.name"
                                tabindex="4"
                        >
                        </a>
                    </li>
                </ul>

                <ul
                        *ngIf="!(_sitesLength$ | async) && searchTerm"
                        class="ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all siteSelect"
                >
                    <li class="ui-menu-item">
                        <a class="ui-corner-all" tabindex="-1">{{ ('SitesManager_NotFound'|translate) + ' ' + searchTerm }}</a>
                    </li>
                </ul>
            </div>

            <div
                    *ngIf="allSitesLocation=='bottom' && showAllSitesItem"
            >
                <site-selector-all-sites-link
                        [allSitesText]="allSitesText"
                        (onClickLink)="onClickAllSitesLink($event)"
                >
                </site-selector-all-sites-link>
            </div>
        </div>
    </div>
    `,
})
export class SiteSelectorComponent implements OnInit {
    constructor(private sitesService: SitesService, private sanitizer: DomSanitizer) {}

    @Input() showSelectedSite: boolean = false;
    @Input() showAllSitesItem: boolean = true;
    @Input() switchSiteOnSelect: boolean = true;
    @Input() onlySitesWithAdminAccess: boolean = false;
    @Input() name: string = '';
    @Input() allSitesText: string = _pk_translate('General_MultiSitesSummary');
    @Input() allSitesLocation: string = 'bottom';
    @Input() placeholder: string = '';
    @Input() siteid?: string;
    @Input() sitename?: string;
    @Output() onSelectedSiteChange: EventEmitter<SiteRef> = new EventEmitter<SiteRef>();

    showSitesList: boolean = false;
    selectedSite?: SiteRef;
    isLoading: boolean = false;
    searchTerm: string = '';
    readonly activeSiteId: number|string = (window as any).piwik.idSite;
    private _firstLoad: boolean = true;

    private _sitesSubject: BehaviorSubject<Site[]> = new BehaviorSubject<Site[]>([]);
    private _changes$: BehaviorSubject<SimpleChanges> = new BehaviorSubject<SimpleChanges>({});

    readonly autocompleteMinSites$ = this.sitesService.getNumWebsitesToDisplayPerPage();

    readonly _sites$: Observable<Site[]> = this._sitesSubject.asObservable();
    readonly _hasMultipleWebsites$ = this._sites$.pipe(map(sites => sites.length > 1));
    readonly _hasOnlyOneSite$ = this._hasMultipleWebsites$.pipe(map(x => !x));
    readonly _firstSiteName$ = this._sites$.pipe(map(x => x?.[0]?.name));
    readonly _sitesLength$ = this._sites$.pipe(map(x => x.length));

    @ViewChild('customSelectInput') _customSelectInput?: ElementRef;
    @ViewChild('selectedSiteDisplay') _selectedSiteDisplay?: ElementRef;
    @ViewChildren('listLink') _siteLinks?: QueryList<ElementRef>;

    onClickSelector() {
        this.showSitesList = !this.showSitesList;
        if (!this.showSitesList) {
            return;
        }

        if (this.isLoading) {
            return;
        }

        this._loadInitialSites();
    }

    ngOnInit() {
        this._setInitialSelectedSite();
        this._onShowingSiteListGrabFocus();
        this._onSearchTermChangeHighlightSiteList();
        this._registerShortcuts();
        this._loadInitialSites();
    }

    _setInitialSelectedSite() {
        if (this.siteid && this.sitename) {
            this.selectedSite = {id: this.siteid, name: this.sitename};
        }
    }

    _onShowingSiteListGrabFocus() {
        // NOTE: equivalent of a $watch on the expression in site selector
        this._changes$.pipe(
            combineLatest(this.autocompleteMinSites$, this._sitesLength$),
            map(([changes, autoCompleteMinSites, sitesLength]) => this.showSitesList && (autoCompleteMinSites <= sitesLength || this.searchTerm)),
        ).subscribe(autoFocus => {
            if (autoFocus) {
                this._customSelectInput?.nativeElement?.focus()
            }
        });
    }

    _onSearchTermChangeHighlightSiteList() {
        this._changes$.pipe(
            filter(changes => !! changes.searchTerm),
            map(changes => changes.searchTerm.currentValue),
        ).subscribe(newSearchTermValue => {
            if (!newSearchTermValue) {
                return;
            }

            this._siteLinks?.forEach(({ nativeElement }: ElementRef) => {
                let content = piwikHelper.htmlEntities(nativeElement.textContent);
                const startTerm = content.toLowerCase().indexOf(newSearchTermValue.toLowerCase());

                if (-1 !== startTerm) {
                    const word = content.substring(startTerm, newSearchTermValue.length);
                    const escapedWord = this.sanitizer.sanitize(SecurityContext.NONE, word);
                    content = content.replace(word, '<span class="autocompleteMatched">' + escapedWord + '</span>');
                    nativeElement.innerHTML = content;
                }
            });
        });
    }

    ngOnChanges(changes: SimpleChanges) {
        this._changes$.next(changes);
    }

    searchSite() {
        this.sitesService.searchSites(this.searchTerm).subscribe(sites => this._sitesSubject.next(sites));
    }

    clearSearchTerm() {
        this.searchTerm = '';
        this._loadInitialSites();
    }

    private _loadInitialSites() {
        this.sitesService.loadInitialSites().subscribe(sites => {
            if (this._firstLoad) {
                this._selectInitialSite(sites);
            }

            this._firstLoad = false;
            this._sitesSubject.next(sites);
        });
    }

    private _selectInitialSite(sites: Site[]) {
        if (!this.selectedSite && sites.length == 1) {
            this.selectedSite = {id: sites[0].idsite, name: sites[0].name};
        }
    }

    onClickAllSitesLink(event: MouseEvent) {
        this.switchSite({idsite: 'all', name: this.allSitesText}, event);
        this.showSitesList = false;
    }

    switchSite(switchToSite: { idsite: string|number; name: string }, event: MouseEvent) {
        // for Mac OS cmd key needs to be pressed, ctrl key on other systems
        const controlKey = navigator.userAgent.indexOf("Mac OS X") !== -1 ? event.metaKey : event.ctrlKey;

        if (event && controlKey && (event.target as any)?.href) {
            window.open((event.target as any).href, "_blank");
            return;
        }

        this.selectedSite = {id: switchToSite.idsite, name: switchToSite.name};

        const activeSiteId: string|number = (window as any).piwik.idSite;
        if (!this.switchSiteOnSelect || activeSiteId == switchToSite.idsite) {
            this.onSelectedSiteChange.emit(this.selectedSite);
            return;
        }

        this.loadSite(switchToSite.idsite);
    }

    loadSite(idSite: string|number) {
        if (idSite == 'all') {
            document.location.href = piwikHelper.getCurrentQueryStringWithParametersModified(piwikHelper.getQueryStringFromParameters({
                module: 'MultiSites',
                action: 'index',
                date: piwik.currentDateString,
                period: piwik.period,
            }));
        } else {
            piwik.broadcast.propagateNewPage('segment=&idSite=' + idSite, false);
        }
    }

    getUrlForSiteId(idSite: string|number) {
        const idSiteParam   = 'idSite=' + idSite;
        const newParameters = 'segment=&' + idSiteParam;
        const hash = piwik.broadcast.isHashExists() ? piwik.broadcast.getHashFromUrl() : "";
        return piwik.helper.getCurrentQueryStringWithParametersModified(newParameters) +
            '#' + piwik.helper.getQueryStringWithParametersModified(hash.substring(1), newParameters);
    }

    private _registerShortcuts() {
        piwikHelper.registerShortcut('w', _pk_translate('CoreHome_ShortcutWebsiteSelector'), (event: KeyboardEvent) => {
            if (event.altKey) {
                return;
            }
            if (event.preventDefault) {
                event.preventDefault();
            } else {
                event.returnValue = false; // IE
            }

            this.onClickSelector();
            this._selectedSiteDisplay?.nativeElement.focus();
        });
    }
}

<div #rootdiv
     focusAnywhereButHere
     (onLoseFocus)="showSitesList=false"
     class="siteSelector piwikSelector borderedControl"
     [attr.class]="{expanded: showSitesList, disabled: (_hasOnlyOneSite$ | async)}">

    <input *ngIf="name" type="hidden" [attr.name]="name" [value]="selectedSite?.id"/>

    <a
        #selectedSiteDisplay
        (click)="onClickSelector()"
        (keyup.enter)="onClickSelector()"
        href="javascript:void(0)"
        [attr.title]="(_hasMultipleWebsites$ | async) ? ('CoreHome_ChangeCurrentWebsite'|translate) : ''"
        [attr.class]="{loading:isLoading,title:true}"
        tabindex="4"
    >
        <span [attr.class]="{icon:true,'icon-arrow-bottom':true,iconHidden:isLoading,collapsed:!showSitesList}"></span>
        <span>
            <span *ngIf="selectedSite?.name || !placeholder">{{ selectedSite?.name || (_firstSiteName$|async) }}</span>
            <span *ngIf="!selectedSite?.name && placeholder">{{ placeholder }}</span>
        </span>
    </a>

    <div *ngIf="showSitesList" class="dropdown">
        <div class="custom_select_search" *ngIf="((autocompleteMinSites$|async) || 0) <= ((_sitesLength$|async) || 0) || searchTerm">
            <input
                #customSelectInput
                type="text"
                (click)="searchTerm=''"
                [(ngModel)]="searchTerm"
                (change)="searchSite()"
                [attr.placeholder]="'General_Search'|translate"
                tabindex="4"
                class="websiteSearch inp browser-default"
            />
            <!-- TODO: translate Clear? -->
            <img title="Clear"
                 *ngIf="searchTerm"
                 (click)="clearSearchTerm()"
                 class="reset"
                 src="plugins/CoreHome/images/reset_search.png"
             />
        </div>

        <div
            *ngIf="allSitesLocation=='top' && showAllSitesItem"
        >
            <site-selector-all-sites-link
                [allSitesText]="allSitesText"
                (onClickLink)="onClickAllSitesLink($event)"
            >
            </site-selector-all-sites-link>
        </div>

        <div class="custom_select_container">
            <ul class="custom_select_ul_list" (click)="showSitesList=false">
                <!-- !showSelectedSite && activeSiteId==site.idsite -->
                <li
                    *ngFor="let site in (_sites$|async)"
                    (click)="switchSite(site, $event)"
                    [hidden]="!showSelectedSite && activeSiteId == site.idsite"
                >
                    <a
                        #listLink
                        (click)="$event.preventDefault()"
                        [attr.href]="getUrlForSiteId(site.idsite)"
                        [attr.title]="site.name"
                        [innerHTML]="site.name"
                        tabindex="4"
                    >
                    </a>
                </li>
            </ul>

            <ul
                *ngIf="!(_sitesLength$ | async) && searchTerm"
                class="ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all siteSelect"
            >
                <li class="ui-menu-item">
                    <a class="ui-corner-all" tabindex="-1">{{ ('SitesManager_NotFound'|translate) + ' ' + searchTerm }}</a>
                </li>
            </ul>
        </div>

        <div
            *ngIf="allSitesLocation=='bottom' && showAllSitesItem"
        >
            <site-selector-all-sites-link
                [allSitesText]="allSitesText"
                (onClickLink)="onClickAllSitesLink($event)"
            >
            </site-selector-all-sites-link>
        </div>
    </div>
</div>
