// plugins/Feedback/vue/src/RateFeature/RateFeature.vue
<!--
  Matomo - free/libre analytics platform
  @link https://matomo.org
  @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
-->

<template>
  <div
    :title="translate('Feedback_RateFeatureTitle', $sanitize(title))"
    class="ratefeature"
  >
    <div
      class="iconContainer"
      v-on:mouseenter="expanded = true"
      v-on:mouseleave="expanded = false"
    >
      <img
        v-on:click="likeFeature();"
        class="like-icon"
        src="plugins/Feedback/vue/src/RateFeature/thumbs-up.png"
      />
      <img
        v-on:click="dislikeFeature();"
        class="dislike-icon"
        src="plugins/Feedback/vue/src/RateFeature/thumbs-down.png"
      />
    </div>
    <MatomoDialog
      v-model="showFeedbackForm"
      @yes="sendFeedback()"
      @validation = "sendFeedback()"
    >
      <div
        class="ui-confirm ratefeatureDialog"
      >
        <h2>{{ translate('Feedback_RateFeatureThankYouTitle', title) }}</h2>
        <br />
        <div
          v-if="like"
        >
          <p v-if="title" >{{ translate('Feedback_RateFeatureLeaveMessageLikeNamedFeature',
          title) }}</p>
          <p v-if="!title" >{{ translate('Feedback_RateFeatureLeaveMessageLike') }}</p>
          <br />
          <div class="row">
            <div class="col l6 offset-l3" style="text-align:left">
              <label for="useful" class="ratelabel">
                <input type="radio" id="useful" value="useful" v-model="likeReason"
                       class="rateradio">
                {{ translate('Feedback_RateFeatureUsefulInfo') }}
              </label>
              <br />
              <label for="easy" class="ratelabel">
                <input type="radio" id="easy" value="easy" v-model="likeReason" class="rateradio">
                {{ translate('Feedback_RateFeatureEasyToUse') }}
              </label>
              <br />
              <label for="configurable" class="ratelabel">
                <input type="radio" id="configurable" value="configurable" v-model="likeReason"
                       class="rateradio">
                {{ translate('Feedback_RateFeatureConfigurable') }}
              </label>
              <br />
              <label for="likeother" class="ratelabel">
                <input type="radio" id="likeother" value="likeother" v-model="likeReason"
                       class="rateradio">
                {{ translate('Feedback_RateFeatureOtherReason') }}
              </label>
            </div>
          </div>

        </div>
        <div
          v-if="!like"
        >
          <p v-if="title">{{ translate('Feedback_RateFeatureLeaveMessageDislikeNamedFeature',
            title) }}</p>
          <p v-if="!title">{{ translate('Feedback_RateFeatureLeaveMessageDislike') }}</p>
          <br />
          <div class="row">
            <div class="col l6 offset-l3" style="text-align:left">
              <label for="missingfeatures" class="ratelabel">
                <input type="radio" id="missingfeatures" value="missingfeatures"
                       v-model="dislikeReason" class="rateradio">
                {{ translate('Feedback_RateFeatureDislikeAddMissingFeatures') }}
              </label>
              <br />
              <label for="makeeasier" class="ratelabel">
                <input type="radio" id="makeeasier" value="makeeasier" v-model="dislikeReason"
                       class="rateradio">
                {{ translate('Feedback_RateFeatureDislikeMakeEasier') }}
              </label>
              <br />
              <label for="speedup" class="ratelabel">
                <input type="radio" id="speedup" value="speedup" v-model="dislikeReason"
                       class="rateradio">
                {{ translate('Feedback_RateFeatureDislikeSpeedUp') }}
              </label>
              <br />
              <label for="fixbugs" class="ratelabel">
                <input type="radio" id="fixbugs" value="fixbugs" v-model="dislikeReason"
                       class="rateradio">
                {{ translate('Feedback_RateFeatureDislikeFixBugs') }}
              </label>
              <br />
              <label for="dislikeother" class="ratelabel">
                <input type="radio" id="dislikeother" value="dislikeother" v-model="dislikeReason"
                       class="rateradio">
                {{ translate('Feedback_RateFeatureOtherReason') }}
              </label>
              <br />
            </div>
          </div>

        </div>

        <div v-if="likeReason || dislikeReason" class="messageContainer">

          <p v-if="likeReason" v-html="translate('Feedback_RateFeatureLeaveMessageLikeExtra',
            `<i class='icon-heart red-text'></i>`)"></p>

          <p v-if="dislikeReason && dislikeReason == 'missingfeatures'"
             v-html="translate('Feedback_RateFeatureLeaveMessageDislikeExtraMissing',
            `<i class='icon-heart red-text'></i>`)"></p>

          <p v-if="dislikeReason && dislikeReason == 'makeeasier'"
             v-html="translate('Feedback_RateFeatureLeaveMessageDislikeExtraEasier',
            `<i class='icon-heart red-text'></i>`)"></p>

          <p v-if="dislikeReason && dislikeReason == 'fixbugs'"
             v-html="translate('Feedback_RateFeatureLeaveMessageDislikeExtraBugs',
            `<i class='icon-heart red-text'></i>`)"></p>

          <p v-if="dislikeReason &&
          (dislikeReason == 'dislikeother' || dislikeReason == 'speedup')"
             v-html="translate('Feedback_RateFeatureLeaveMessageDislikeExtra',
            `<i class='icon-heart red-text'></i>`)"></p>

          <div class="error-text" v-if="errorMessage">{{ errorMessage }}</div>
          <textarea :class="{'has-error':errorMessage}" v-model="feedbackMessage"/>
        </div>

        <input
          class="btn"
          type="button"
          role="validation"
          :title="translate('Feedback_RateFeatureSendFeedbackInformation')"
          :value="translate('Feedback_SendFeedback')"
        />

        <input
          type="button"
          role="cancel"
          :value="translate('General_Cancel')"
        />
      </div>
    </MatomoDialog>

    <MatomoDialog
      v-model="ratingDone"
    >
      <div
        class="ui-confirm ratefeatureDialog"
      >
        <h2 v-html="translate('Feedback_ThankYouHeart',`<i class='icon-heart red-text'></i>`)"></h2>
        <div
          v-if="like"
        >
          <ReviewLinks />
        </div>
        <p v-if="!like">{{ translate('Feedback_AppreciateFeedback') }}</p>
        <input
          type="button"
          :value="translate('General_Close')"
          role="yes"
        />
      </div>
    </MatomoDialog>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { MatomoDialog, AjaxHelper } from 'CoreHome';
import ReviewLinks from '../ReviewLinks/ReviewLinks.vue';

const { $ } = window;

export default defineComponent({
  props: {
    title: String,
  },
  components: {
    MatomoDialog,
    ReviewLinks,
  },
  data() {
    return {
      like: false,
      likeReason: null,
      dislikeReason: null,
      ratingDone: false,
      expanded: false,
      showFeedbackForm: false,
      feedbackMessage: '',
      errorMessage: null,
    };
  },
  methods: {
    dislikeFeature() {
      this.ratingDone = false;
      this.like = false;
      this.showFeedbackForm = true;
      this.errorMessage = null;
      this.likeReason = null;
      this.dislikeReason = null;
    },
    likeFeature() {
      this.ratingDone = false;
      this.like = true;
      this.showFeedbackForm = true;
      this.errorMessage = null;
      this.likeReason = null;
      this.dislikeReason = null;
    },

    async sendFeedback() {
      this.errorMessage = null;
      const res = await AjaxHelper.fetch({
        method: 'Feedback.sendFeedbackForFeature',
        featureName: this.title,
        like: this.like ? '1' : '0',
        choice: this.like ? this.likeReason : this.dislikeReason,
        message: this.feedbackMessage,
      });

      if (res.value === 'success') {
        $('.modal').modal('close');
        this.ratingDone = true;
        this.feedbackMessage = '';
      } else {
        this.errorMessage = res.value;
      }
    },
  },
});
</script>

// plugins/CoreHome/angular/src/lib/rate-feature/rate-feature.component.ts
import {Component, EventEmitter, Input, Output} from "@angular/core";
import {MatomoApiService} from "../matomo-api/matomo-api.service";

@Component({
    selector: 'review-links',
    template: `
        <div class="requestReview">
            <p>{{ 'Feedback_PleaseLeaveExternalReviewForMatomo'|translate }}</p><br/><br/>

            <div class="review-links">
                <div class="review-link">
                    <a href="https://www.capterra.com/p/182627/Matomo-Analytics/" target="_blank">
                        <div class="image"><img loading="lazy" src="plugins/Feedback/images/capterra.svg"></div>
                        <div class="link">Capterra</div>
                    </a>
                </div>

                <div class="review-link">
                    <a href="https://www.g2crowd.com/products/matomo-formerly-piwik/details" target="_blank">
                        <div class="image"><img loading="lazy" src="plugins/Feedback/images/g2crowd.svg"></div>
                        <div class="link">G2 Crowd</div>
                    </a>
                </div>

                <div class="review-link">
                    <a href="https://www.producthunt.com/posts/matomo-2" target="_blank">
                        <div class="image"><img loading="lazy" src="plugins/Feedback/images/producthunt.svg"></div>
                        <div class="link">Product Hunt</div>
                    </a>
                </div>

                <div class="review-link">
                    <a href="https://www.saasworthy.com/product/matomo" target="_blank">
                        <div class="image"><img loading="lazy" src="plugins/Feedback/images/saasworthy.png"></div>
                        <div class="link">SaaSworthy</div>
                    </a>
                </div>

                <div class="review-link">
                    <a href="https://www.trustradius.com/products/matomo/reviews" target="_blank">
                        <div class="image"><img loading="lazy" src="plugins/Feedback/images/trustradius.svg"></div>
                        <div class="link">TrustRadius</div>
                    </a>
                </div>
            </div>
        </div>
    `,
})
export class ReviewLinksComponent {
    // empty
}

@Component({
    selector: 'rate-feature',
    template: `
        <div title="{{ 'Feedback_RateFeatureTitle'|translate:(title) }}" class="ratefeature">
            <div
                class="iconContainer"
                (mouseenter)="expanded = true"
                (mouseleave)="expanded = false"
            >
                <img (click)="likeFeature()" class="like-icon" src="plugins/Feedback/angularjs/ratefeature/thumbs-up.png"/>
                <img *ngIf="expanded" (click)="dislikeFeature()" class="dislike-icon"
                     src="plugins/Feedback/angularjs/ratefeature/thumbs-down.png"/>
            </div>
            
            <div matomoDialog class="ui-confirm ratefeatureDialog" [showModal]="showFeedbackForm" (onYesClick)="sendFeedback()" (onClose)="showFeedbackForm = false">
                <h2>{{ 'Feedback_RateFeatureThankYouTitle'|translate:title }}</h2>
                <p *ngIf="like">{{ 'Feedback_RateFeatureLeaveMessageLike'|translate }}</p>
                <p *ngif="!like">{{ 'Feedback_RateFeatureLeaveMessageDislike'|translate }}</p>
                <br />

                <div class="messageContainer">
                    <textarea [(ngModel)]="feedbackMessage"></textarea>
                </div>

                <input
                    type="button"
                    title="{{ 'Feedback_RateFeatureSendFeedbackInformation'|translate }}"
                    value="{{ 'Feedback_SendFeedback'|translate }}"
                    role="yes"
                />
                <input type="button" role="cancel" value="{{ 'General_Cancel'|translate }}"/>
            </div>

            <div matomoDialog class="ui-confirm ratefeatureDialog" [showModal]="ratingDone" (onClose)="showFeedbackForm = false">
                <h2>{{ 'Feedback_ThankYou'|translate:title }}</h2>

                <review-links *ngIf="like" src="'plugins/Feedback/angularjs/feedback-popup/review-links.directive.html'"></review-links>

                <input type="button" value="{{ 'General_Ok'|translate }}" role="yes"/>
            </div>
        </div>
    `,
})
export class RateFeatureComponent {
    constructor(private matomoApi: MatomoApiService) {}

    @Input() title: string = '';

    expanded: boolean = false;
    showFeedbackForm: boolean = false;
    feedbackMessage: string = '';
    like: boolean = false;
    ratingDone: boolean = false;

    likeFeature() {
        this.like = true;
        this.showFeedbackForm = true;
    }

    dislikeFeature() {
        this.like = false;
        this.showFeedbackForm = true;
    }

    async sendFeedback() {
        await this.sendFeedbackForFeature(this.title, this.like, this.feedbackMessage);
        this.ratingDone = true;
    }

    sendFeedbackForFeature(featureName: string, like: boolean, message: string) {
        return this.matomoApi.fetch({
            method: 'Feedback.sendFeedbackForFeature',
            featureName: featureName,
            like: like ? '1' : '0',
            message: message + '',
        }).toPromise();
    }
}
